  # Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Jann Claude
tagline:             'My tech && untech multipurpose personal blog'
description:         'My name is Jann Claude, I am a christian, web developer, rock climber, pc gamer, working hard to become a better person, every single day.'
url:                 http://janncm.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jann Claude Mousquer
  url:               https://twitter.com/janncm
  email:             jannclaude@gmail.com
  github:            https://github.com/janncm
  linkedin:          https://linkedin.com/in/janncm/en

# Custom vars
version:             1.0.1
