# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Jann
tagline:             'A personal blog'
description:         'Personal and professional experiences shared with you.'
url:                 http://janncm.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jann Claude Mousquer
  url:               https://twitter.com/janncm
  email:             jannclaude@gmail.com
  github:            https://github.com/janncm
  linkedin:          https://linkedin.com/in/janncm/en

# Custom vars
version:             1.0.0
